import Layout from "@/components/layout";
import { ThemeProvider } from "@/context/ThemeContext";
import "@/styles/globals.css";
import Head from "next/head";

export default function App({ Component, pageProps }) {
  const getLayout =
    Component.getLayout ??
    ((page) => <Layout activeDots={Component.activeDots}>{page}</Layout>);

  return (
    <>
      <Head>
        <title>Personal Portfolio Websites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon/favicon.ico" />
      </Head>
      <ThemeProvider>{getLayout(<Component {...pageProps} />)}</ThemeProvider>
    </>
  );
}
